### ISSUE TITLE
Error: No Video Found 

### ISSUE THREAD

**Issue by chen-rn** [lucataco/cog-MagicAnimate#1]
![image](https://github.com/lucataco/cog-MagicAnimate/assets/36214945/d8cdf7e0-c776-42cf-a9a2-120cff4af848)
```
{
  "completed_at": "2023-12-05T22:19:29.681267Z",
  "created_at": "
2023-12-05T22:17:22.584585Z",
  "error": null,
  "id": "f5ck77rbbr6kjk2ag7eltz3uu4",
  "input": {
    "image": "https://replicate.delivery/pbxt/JzwQDHJAGGLKT2mLONWKQkIHXVBiXzsZ15u20xqHPkk0UiZD/IMG_3024%201.png",
    "video": "https://replicate.delivery/pbxt/JzgM380MyPyDjbgkCYGGPg1g2NWiV50W4PmD52JPIsjh9R9G/running.mp4",
    "guidance_scale": 7.5,
    "num_inference_steps": 25
  },
  "logs": "Using seed: 28957\n/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.\nfrom diffusers.pipeline_utils import DiffusionPipeline\nloaded temporal unet's pretrained weights from /src/pretrained_models/stable-diffusion-v1-5/unet ...\n### missing keys: 560;\n### unexpected keys: 0;\n### Temporal Module Parameters: 417.1376 M\nThe config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'conditioning_channels': 3, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'global_pool_conditions': False, 'num_attention_heads': None, 'transformer_layers_per_block': 1} were passed to ControlNetModel, but are not expected and will be ignored. Please verify your config.json configuration file.\nIt is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.\nIt is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.\nIt is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.\nIt is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.\n/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:103: FutureWarning: The configuration file of this scheduler: DDIMScheduler {\n\"_class_name\": \"DDIMScheduler\",\n\"_diffusers_version\": \"0.21.4\",\n\"beta_end\": 0.012,\n\"beta_schedule\": \"linear\",\n\"beta_start\": 0.00085,\n\"clip_sample\": true,\n\"clip_sample_range\": 1.0,\n\"dynamic_thresholding_ratio\": 0.995,\n\"num_train_timesteps\": 1000,\n\"prediction_type\": \"epsilon\",\n\"rescale_betas_zero_snr\": false,\n\"sample_max_value\": 1.0,\n\"set_alpha_to_one\": true,\n\"steps_offset\": 0,\n\"thresholding\": false,\n\"timestep_spacing\": \"leading\",\n\"trained_betas\": null\n}\nis outdated. `steps_offset` should be set to 1 instead of 0. Please make sure to update the config accordingly as leaving `steps_offset` might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file\ndeprecate(\"steps_offset!=1\", \"1.0.0\", deprecation_message, standard_warn=False)\n/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:116: FutureWarning: The configuration file of this scheduler: DDIMScheduler {\n\"_class_name\": \"DDIMScheduler\",\n\"_diffusers_version\": \"0.21.4\",\n\"beta_end\": 0.012,\n\"beta_schedule\": \"linear\",\n\"beta_start\": 0.00085,\n\"clip_sample\": true,\n\"clip_sample_range\": 1.0,\n\"dynamic_thresholding_ratio\": 0.995,\n\"num_train_timesteps\": 1000,\n\"prediction_type\": \"epsilon\",\n\"rescale_betas_zero_snr\": false,\n\"sample_max_value\": 1.0,\n\"set_alpha_to_one\": true,\n\"steps_offset\": 1,\n\"thresholding\": false,\n\"timestep_spacing\": \"leading\",\n\"trained_betas\": null\n}\nhas not set the configuration `clip_sample`. `clip_sample` should be set to False in the configuration file. Please make sure to update the config accordingly as not setting `clip_sample` in the config might lead to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file\ndeprecate(\"clip_sample not set\", \"1.0.0\", deprecation_message, standard_warn=False)\ncurrent seed: 28957\n  0%|          | 0/1 [00:00<?, ?it/s]/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:624: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'.\nnum_channels_latents = self.unet.in_channels\n0%|          | 0/1 [00:01<?, ?it/s]\nTraceback (most recent call last):\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\nreturn _run_code(code, main_globals, None,\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/runpy.py\", line 86, in _run_code\nexec(code, run_globals)\nFile \"/src/magic-animate/magicanimate/pipelines/animation.py\", line 282, in <module>\nrun(args)\nFile \"/src/magic-animate/magicanimate/pipelines/animation.py\", line 271, in run\nmain(args)\nFile \"/src/magic-animate/magicanimate/pipelines/animation.py\", line 197, in main\nsample = pipeline(\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\nreturn func(*args, **kwargs)\nFile \"/src/magic-animate/magicanimate/pipelines/pipeline_animation.py\", line 654, in __call__\nref_image_latents = self.images2latents(source_image[None, :], latents_dtype).cuda()\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\nreturn func(*args, **kwargs)\nFile \"/src/magic-animate/magicanimate/pipelines/pipeline_animation.py\", line 394, in images2latents\nlatents.append(self.vae.encode(images[frame_idx:frame_idx+1])['latent_dist'].mean * 0.18215)\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py\", line 46, in wrapper\nreturn method(self, *args, **kwargs)\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py\", line 260, in encode\nh = self.encoder(x)\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1501, in _call_impl\nreturn forward_call(*args, **kwargs)\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/models/vae.py\", line 112, in forward\nsample = self.conv_in(sample)\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1501, in _call_impl\nreturn forward_call(*args, **kwargs)\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 463, in forward\nreturn self._conv_forward(input, self.weight, self.bias)\nFile \"/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 459, in _conv_forward\nreturn F.conv2d(input, weight, bias, self.stride,\nRuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 512, 512] to have 3 channels, but got 4 channels instead",
  "metrics": {
    "predict_time": 39.299323
  },
  "output": "No video found",
  "started_at": "2023-12-05T22:18:50.381944Z",
  "status": "succeeded",
  "urls": {
    "get": "https://api.replicate.com/v1/predictions/f5ck77rbbr6kjk2ag7eltz3uu4",
    "cancel": "https://api.replicate.com/v1/predictions/f5ck77rbbr6kjk2ag7eltz3uu4/cancel"
  },
  "version": "e24ad72cc67dd2a365b5b909aca70371bba62b685019f4e96317e59d4ace6714"
}
```

**Comment by chen-rn** [comment]
Here are some error logs from another attempt!

```
Using seed: 24127
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
0it [00:00, ?it/s]
/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
from diffusers.pipeline_utils import DiffusionPipeline
loaded temporal unet's pretrained weights from /src/pretrained_models/stable-diffusion-v1-5/unet ...
### missing keys: 560;
### unexpected keys: 0;
### Temporal Module Parameters: 417.1376 M
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'conditioning_channels': 3, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'global_pool_conditions': False, 'num_attention_heads': None, 'transformer_layers_per_block': 1} were passed to ControlNetModel, but are not expected and will be ignored. Please verify your config.json configuration file.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:103: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
"_class_name": "DDIMScheduler",
"_diffusers_version": "0.21.4",
"beta_end": 0.012,
"beta_schedule": "linear",
"beta_start": 0.00085,
"clip_sample": true,
"clip_sample_range": 1.0,
"dynamic_thresholding_ratio": 0.995,
"num_train_timesteps": 1000,
"prediction_type": "epsilon",
"rescale_betas_zero_snr": false,
"sample_max_value": 1.0,
"set_alpha_to_one": true,
"steps_offset": 0,
"thresholding": false,
"timestep_spacing": "leading",
"trained_betas": null
}
is outdated. `steps_offset` should be set to 1 instead of 0. Please make sure to update the config accordingly as leaving `steps_offset` might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
deprecate("steps_offset!=1", "1.0.0", deprecation_message, standard_warn=False)
/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:116: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
"_class_name": "DDIMScheduler",
"_diffusers_version": "0.21.4",
"beta_end": 0.012,
"beta_schedule": "linear",
"beta_start": 0.00085,
"clip_sample": true,
"clip_sample_range": 1.0,
"dynamic_thresholding_ratio": 0.995,
"num_train_timesteps": 1000,
"prediction_type": "epsilon",
"rescale_betas_zero_snr": false,
"sample_max_value": 1.0,
"set_alpha_to_one": true,
"steps_offset": 1,
"thresholding": false,
"timestep_spacing": "leading",
"trained_betas": null
}
has not set the configuration `clip_sample`. `clip_sample` should be set to False in the configuration file. Please make sure to update the config accordingly as not setting `clip_sample` in the config might lead to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
deprecate("clip_sample not set", "1.0.0", deprecation_message, standard_warn=False)
current seed: 24127
  0%|          | 0/1 [00:00<?, ?it/s]/src/magic-animate/magicanimate/pipelines/pipeline_animation.py:624: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
num_channels_latents = self.unet.in_channels
0%|          | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/root/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/src/magic-animate/magicanimate/pipelines/animation.py", line 282, in <module>
run(args)
File "/src/magic-animate/magicanimate/pipelines/animation.py", line 271, in run
main(args)
File "/src/magic-animate/magicanimate/pipelines/animation.py", line 197, in main
sample = pipeline(
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/src/magic-animate/magicanimate/pipelines/pipeline_animation.py", line 654, in __call__
ref_image_latents = self.images2latents(source_image[None, :], latents_dtype).cuda()
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/src/magic-animate/magicanimate/pipelines/pipeline_animation.py", line 394, in images2latents
latents.append(self.vae.encode(images[frame_idx:frame_idx+1])['latent_dist'].mean * 0.18215)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
return method(self, *args, **kwargs)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 260, in encode
h = self.encoder(x)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/models/vae.py", line 112, in forward
sample = self.conv_in(sample)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
return self._conv_forward(input, self.weight, self.bias)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 512, 512] to have 3 channels, but got 4 channels instead

```

**Comment by lucataco** [comment]
For now plz use JPG not PNG images
